name = "katelyatv"
compatibility_date = "2024-09-01"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[[d1_databases]]
binding = "DB"
database_name = "katelyatv-db"
database_id = "e42b3112-7ae0-4880-88f9-1050724fb462"
